# vim: filetype=ruby

# Casks

## General crossplatform
cask "1password"               # 1piece
cask "1password-cli"           # 1piece
cask "brave-browser"           # Browser of choice
cask "cyberduck"               # GUI FTP client
cask "discord"                 # Chat app
cask "flameshot"               # Screen shot tool
cask "kitty"                   # Terminal emulator
cask "obsidian"                # Notes system
cask "private-internet-access" # VPN
cask "visual-studio-code"      # Thicc editor, light IDE
cask "zed"                     # Somewhere between VSCode and Emacs

## macOS-specific
brew "FelixKratz/formulae/borders" # JankyBorders
cask "karabiner-elements"          # Keyboard manipulation/remapping
cask "raycast"                     # Launcher
cask "microsoft-remote-desktop"    # MSFT RDP
cask "amethyst"                    # Tiling window manager

brew "mas" # Mac App Store
mas "WireGuard", id: 1451685025

# Non-cask packages

## CLI
brew "atuin"               # CLI history in searchable sqlite
brew "bat"                 # Better cat
brew "direnv"              # Automatically source .envrc upon dir navigation
brew "fd"                  # Alternative to find
brew "figlet"              # ASCyII art text generator
brew "fzf"                 # TUI/CLI fuzzy finder
brew "gh"                  # GitHub CLI
brew "git"                 # Git version control
brew "jq"                  # JSON Query tool
brew "lolcat"              # The purrfect addition to the CLI
brew "nushell"             # "Everything is data" interactive shell
brew "ripgrep"             # Fast search tool
brew "starship"            # Prompt
brew "tldr"                # Short alternative to man-pages
brew "tree"                # Show directory structure visually
brew "uutils-coreutils"    # Modern coreutils rewritten in Rust and MIT licensed
brew "wget"                # Gets things from the web
brew "zoxide"              # Smart `cd` alternative
brew "zsh"                 # Ye old faithful interactive shell
brew "wget"                # Gets things from the W

## TUI
brew "neovim"              # NeoVim terminal-based text editor
brew "ranger"              # Terminal file manager
brew "television"          # General purpose fuzzy finder TUI

## Ranger (TUI File manager) deps
brew "pillow"              # Image manipulation library
brew "mupdf"               # PDF rocessing
brew "pandoc"              # MS/Open Office processing

## Programming
brew "ccache"              # Compiler Cache to speed up some compilations
brew "cmake"               # Configurable cross platform make
brew "dotnet"              # .Net Core (used by some NeoVim extensions)
brew "go"                  # Go programming language
brew "gopls"               # Go languago server
brew "llvm"                # Next-gen compiler backend
brew "lua-language-server" # As the name implies
brew "luarocks"            # Package manager for Lua
brew "marksman"            # Markdown language server
brew "ncurses"             # TUI tooling
brew "nvm"                 # Node Version Manager (Node JS)
brew "pipx"                # Python binaries package manager
brew "poetry"              # Python dependency manager
brew "pyenv"               # Python version manager
brew "python3"             # A snake that runs code
brew "rbenv"               # Ruby environment management
brew "ruby-build"          # Install various Ruby versions and implementations
brew "rustup"              # Rust toolchain
brew "stylua"              # Lua formatter
brew "tio"                 # Serial IO/TTY
brew "yarn"                # NPM alternative, ish
brew "zig"                 # Zig Programming language
### Apple-specific:
brew "fastlane"            # Build tool for Apple platform apps
brew "swiftformat"         # Formatter for Swift
brew "swiftlint"           # Linter for Swift
brew "xcbeautify"          # Beautifier for XCode things
brew "xcode-build-server"  # Do Xcode things outside of Xcode
brew "xcodegen"            # Xcode projects using dir structure and project spec

## Infrastructure related
brew "kubectl"                 # Kubernetes client
brew "libpq"                   # Postgres client (psql)
brew "terraform"               # Infrastructure as Code platform

## ZMK dependencies
brew "ccache"
brew "cmake"
brew "dfu-util"
brew "dtc"
brew "dtc"
brew "gperf"
brew "libmagic"
brew "ninja"
brew "python3"
brew "qemu"
brew "west"

## Networking
brew "wireguard-tools"     # wg command
