#!/bin/sh
# vi: set fs=sh
set -e

# Assumpions:
# - $GDOT_HOME is set (see ~/.zshrc)
# - $GDOT_GIT_DIR is set (see ~/.zshrc)
if [ -z "$GDOT_HOME" ]; then
  echo "env var GDOT_HOME not set"
  exit 1
fi
if [ -z "$GDOT_GIT_DIR" ]; then
  echo "env var GDOT_GIT_DIR not set"
  exit 1
fi

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
if [ "$OS" = "darwin" ]; then
  SETTINGS_SCRIPT="$GDOT_HOME/macos/settings.sh"
elif [ "$OS" = "linux" ]; then
  . /etc/os-release
  DISTRO_ID=${ID,,} # Convert to lowercase for consistent matching
  DISTRO_VERSION=${VERSION_ID}
  SETTINGS_SCRIPT="$GDOT_HOME/linux/$DISTRO_ID/settings.sh"
else
  echo "Unexpected operating system: $OS"
  exit 1
fi

if [ "$#" = 0 ]; then
  echo "Usage: $0 [command] [args]"
  echo "Gdot Commands:"
  echo ""
  echo "  brew          Sync Homebrew bundle file (Brewfile)"
  echo "  brew edit     Edit Homebrew bundle file (Brewfile)"
  echo "  brew install  Install Homebrew"
  echo ""
  echo "  tm            Apply Time Machine exclusions (macOS)"
  echo ""
  echo "  settings      Apply system settings ($SETTINGS_SCRIPT)"
  echo ""
  echo '  sync          Runs "everything": brew && settings'
  echo ""
  echo "  [git cmd]     Any valid Git commands"
  echo ""
fi

COMMAND="$1"
shift
SUBCOMMAND="$1"

case "$COMMAND" in
"brew")
  if [ "$OS" == "darwin" ]; then
	BREWFILE="$GDOT_HOME/macos/Brewfile"
  elif [ "$OS" == "linux" ]; then
	BREWFILE="$GDOT_HOME/linux/common/Brewfile"
  fi
  case "$SUBCOMMAND" in
  edit)
    "$EDITOR" "$BREWFILE"
	;;
  install)
    NONINTERACTIVE=1 /bin/bash -c \
	  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	;;
  "")
    brew bundle --file="$BREWFILE"
	;;
  *)
	  echo "invalid subcommand: $SUBCOMMAND"
	  exit 1
  esac
  ;;

"tm")
  if [ "$OS" -ne "Darwin" ]; then
    echo "$COMMAND is only for macOS; detected $OS"
    exit 1
  fi
  TM_FILE="$GDOT_HOME/macos/time_machine.py.sh"
  if [ "$SUBCOMMAND" = "edit" ]; then
    $EDITOR "$TM_FILE"
  else
    "$TM_FILE"
  fi
  ;;

"settings")
  if [ -x "$SETTINGS_SCRIPT" ]; then
    echo "Applying OS-specific settings..."
	"$SETTINGS_SCRIPT"
  else
	echo "No settings file for $OS"
  fi
  ;;

"sync")
  gdot brew
  gdot settings
  ;;

*)
  git --git-dir="$GDOT_GIT_DIR" --work-tree="$HOME" "$COMMAND" "$@"
  ;;

esac
