#!/bin/sh
# vi: fs=sh
set -e

# Assumpions:
# - $GDOT_HOME is set (see ~/.zshrc)
# - $GDOT_GIT_DIR is set (see ~/.zshrc)
if [ -z "$GDOT_HOME" ]; then
  echo "env var GDOT_HOME not set"
  exit 1
fi
if [ -z "$GDOT_GIT_DIR" ]; then
  echo "env var GDOT_GIT_DIR not set"
  exit 1
fi

OS=$(uname -s)
if [ "$OS" = "Darwin" ]; then
  SETTINGS_SCRIPT="macos/settings.sh"
elif [ "$OS" = "Linux" ]; then
  . /etc/os-release
  DISTRO_ID=${ID,,} # Convert to lowercase for consistent matching
  DISTRO_VERSION=${VERSION_ID}
  SETTINGS_SCRIPT="$GDOT_HOME/linux/$DISTRO_ID/settings.sh"
elif [ "$OS" = "FreeBSD" ]; then
  SETTINGS_SCRIPT="none" # none for FreeBSD
else
  echo "Unexpected operating system: $OS"
  # TODO: Linux support
  exit 1
fi

if [ "$#" = 0 ]; then
  echo "Usage: $0 [command] [args]"
  echo "Gdot Commands:"
  echo ""
  echo "  brew          Sync Homebrew bundle file (Brewfile)"
  echo "  brew edit     Edit Homebrew bundle file (Brewfile)"
  echo ""
  echo "  tm            Apply Time Machine exclusions (macOS)"
  echo ""
  echo "  settings      Apply system settings ($SETTINGS_SCRIPT)"
  echo ""
  echo '  sync          Runs "everything": brew && settings'
  echo ""
  echo "  [git cmd]     Any valid Git commands"
  echo ""
fi

COMMAND="$1"
shift
SUBCOMMAND="$1"

case "$COMMAND" in

"brew")
  if [ "$OS" -ne "Darwin" ]; then
    echo "$COMMAND is only for macOS; detected $OS"
    exit 1
  fi
  BREWFILE="$GDOT_HOME/macos/Brewfile"
  if [ "$SUBCOMMAND" = "edit" ]; then
    $EDITOR "$BREWFILE"
  else
    brew bundle --file="$BREWFILE"
  fi
  ;;

"tm")
  if [ "$OS" -ne "Darwin" ]; then
    echo "$COMMAND is only for macOS; detected $OS"
    exit 1
  fi
  TM_FILE="$GDOT_HOME/macos/time_machine.py.sh"
  if [ "$SUBCOMMAND" = "edit" ]; then
    $EDITOR "$TM_FILE"
  else
    "$TM_FILE"
  fi
  ;;

"settings")
  if [ "$OS" = "Darwin" ]; then
    "$GDOT_HOME/$SETTINGS_SCRIPT"
  else
	echo "No settings file for $OS"
  fi
  ;;

"sync")
  if [ "$OS" -ne "Darwin" ]; then
    gdot brew
    gdot settings
  else
	  echo "No sync for OS: $OS"
  fi
  ;;

*)
  git --git-dir="$GDOT_GIT_DIR" --work-tree="$HOME" "$COMMAND" "$@"
  ;;

esac
