#!/usr/bin/env bash

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m \
  config layout float \
  config window_shadow off \
  config window_border_blur off \
  window_border on \
  window_border_width 2 \
  active_window_border_color 0xFFA000FF \
  normal_window_border_color 0x0000FF00 \

echo "yabai configuration loaded..."

