#!/usr/bin/env python3
import os

included_home_subdirs=set("""
.config
.gitconfig
.ssh
Desktop
Documents
Library
Movies
Pictures
Public
Public
inbox
notes
""".strip().split("\n"))

# Q: "What is the inbox folder?"
# A: I purge my downloads folder from time to time. The inbox folder is
#    to move things from ~/Downloads into a place that isn't purged and
#    is still included in my Time Machine backups.

home_dir = os.path.expanduser("~")
home_subdirs = {dir for dir in os.listdir(home_dir) if os.path.isdir(os.path.join(home_dir, dir))}

dirs_to_ignore = {dir for dir in home_subdirs if dir not in included_home_subdirs}

print("Resetting exclusions to default state...")
for dir in home_subdirs:
    os_path = os.path.join(home_dir, dir)
    os.system(f"sudo tmutil removeexclusion -p {os_path}")
print("    done.\n")

for dir in dirs_to_ignore:
    os_path = os.path.join(home_dir, dir)
    os.system(f"sudo tmutil addexclusion -p {os_path}")
    print(f"Added exclusion: {os_path}")

